config/routes.rb
PlazrStore::Engine.routes.draw do

  get 'index' => 'pages#index'
  # root to: 'pages#index'



  root :to => 'pages#index'

  # mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root :to => 'pages#index'
    resources :banners, :only => [:new, :create, :edit, :update]
    resources :brands
    resources :discount_types
    resources :orders, :except => [:new, :create, :edit, :update, :destroy] do
      put 'pay', :on => :member
      match 'ship/:cart_variant_id' => 'orders#ship', :as => :ship_product, :via => :put
    end
    resources :logos, :only => [:new, :create, :edit, :update]
    resources :pages
    resources :product_categories
    resources :products do
      resources :product_properties, :only => [:index, :create, :destroy]
      resources :variants
      resources :multimedia
    end
    resources :promotional_codes
    resources :promotions
    resources :properties
    resources :prototypes
    resources :shipment_conditions
    resources :template_customizations
    resources :variant_properties do
      resources :variant_property_values
    end
    resources :paypal_accounts
    match 'customization' => 'customizations#show', :as => :customization, :via => :get, :controller => 'customizations'
  end

  resources :products, :only => [:index, :show]

  #pages
  scope '/pages' do
    match 'index' => 'pages#index', :via => :get
    match '/:slug' => 'pages#show', :as => :page, :via => :get, :controller => "pages"
  end

  # search controller
  scope '/search' do
    match '/' => 'search#search', :as => :search, :via => :get, :controller => "search"
  end

  # carts controller
  scope '/cart' do
    match '/' => 'cart#show', :as => :cart, :via => :get
    match 'add/:id'    => 'cart#add',    :as => :cart_add,    :via => :post
    match 'remove/:id' => 'cart#remove', :as => :cart_remove, :via => :delete
  end

  scope '/wishlist' do
    match '/' => 'wishlist#show', :as => :wishlist, :via => :get
    match 'add/:id'    => 'wishlist#add',    :as => :wishlist_add,    :via => :post
    match 'remove/:id' => 'wishlist#remove', :as => :wishlist_remove, :via => :delete
  end

  # orders controller
  match 'checkout' => 'orders#new', :as => :checkout, :via => :get
  match 'checkout' => 'orders#create', :as => :checkout, :via => :post
  match 'express_checkout' => 'paypal_express#checkout', :as => :express_checkout
  match 'paypal_express_purchase' => 'paypal_express#purchase', :as => :paypal_express_purchase
  match "receipt" => "orders#receipt", :as => :receipt
  match 'review' => 'orders#review', :as => :review
  scope '/orders' do
    match "/" => "orders#history", :as => :orders_history
    match '/:id' => 'orders#show', :as => :order, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#new', :as => :new_feedback_product, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#create', :as => :feedback_product, :via => :post
  end


  mount PlazrAuth::Engine => '/'
end

app/models/plazr_store/promotional_code.rb
# encoding: utf-8
module PlazrStore
  class PromotionalCode < ActiveRecord::Base
    ## Relations ##
    belongs_to :discount_type

    has_many :orders
    has_one :coupon

    ## Attributes ##
    attr_accessible :code, :description, :discount_type_id, :expires_at, :minimum_cart, :starts_at, :times_used, :uses_allowed, :value

    ## Validations ##
    validates :code, :presence => true
    validates :value, presence: true, numericality: {:greater_than_or_equal_to => 0}
    validates :minimum_cart, numericality: {:greater_than_or_equal_to => 0, :allow_blank => true}
    validates :times_used, numericality: {:greater_than_or_equal_to => 0, :allow_blank => true}
    validates :uses_allowed, numericality: {:greater_than_or_equal_to => -1, :allow_blank => true}
    validates :starts_at, :presence => true
    validate :start_before_expire

    def start_before_expire
      return unless starts_at and expires_at
      errors.add(:starts_at, "needs to be minor or equal to the expire date") unless starts_at < expires_at
    end

  end
end

app/controllers/plazr_store/admin/promotional_codes_controller.rb
# encoding: utf-8
module PlazrStore
  class Admin::PromotionalCodesController < Admin::ApplicationController 

    def show
      @promotional_code = PromotionalCode.find(params[:id]) 
    end

    def index
      @promotional_codes = PromotionalCode.order("starts_at DESC, expires_at ASC")
    end

    def new
      @promotional_code = PromotionalCode.new(:code => SecureRandom.hex(8).upcase)
      @discount_types = DiscountType.promotional_code_types
    end

    def create
      @promotional_code = PromotionalCode.new params[:promotional_code]

      if @promotional_code.save
        redirect_to admin_promotional_code_path(@promotional_code), :notice => 'Código promocional criado com sucesso.' 
      else
        @discount_types = DiscountType.promotional_code_types
        render :new
      end
    end

    def edit
      @promotional_code = PromotionalCode.find(params[:id])
      @discount_types = DiscountType.promotional_code_types
    end

    def update
      @promotional_code = PromotionalCode.find(params[:id])

      if @promotional_code.update_attributes(params[:promotional_code])
        redirect_to admin_promotional_code_path(@promotional_code), :notice => 'Código promocional atualizado com sucesso.' 
      else
        @discount_types = DiscountType.promotional_code_types
        render :edit
      end
    end

    def destroy
      @promotional_code = PromotionalCode.find(params[:id])
      @promotional_code.destroy
      redirect_to admin_promotional_codes_path
    end

    protected

    def get_location
      super
      @tab = 'promotions'
    end
  end
end

app/views/plazr_store/admin/promotional_codes/_form.html.haml
= form_for [:admin, @promotional_code] do |f|
  - if @promotional_code.errors.any?
    #error_explanation
      %h2= "#{pluralize(@promotional_code.errors.count, "error")} prohibited this PromotionalCode from being saved:"
      %div{:class=>["alert","alert-error"]}
        %ul
          - @promotional_code.errors.full_messages.each do |msg|
            %li= msg

  = f.label :code
  = f.text_field :code
  %br

  = f.label :description
  = f.text_field :description
  %br

  = f.label :discount_type
  = f.collection_select :discount_type_id, @discount_types, :id, :name, {:prompt => "Escolha o tipo de desconto"}
  %br

  = f.label :value
  = f.text_field :value
  %br

  = f.label :minimum_cart
  = f.text_field :minimum_cart
  %br

  = f.label :uses_allowed
  = f.text_field :uses_allowed
  %br

  = f.label :starts_at
  = f.text_field :starts_at
  %br

  = f.label :expires_at
  = f.text_field :expires_at
  %br

  //%h4= "Products"
  //= f.fields_for :product_promotions do |pp|
  //  = pp.check_box :_destroy, {:checked => pp.object.product_id.to_s == @prod || @check_prods.include?(pp.object.product_id.to_s) || pp.object.persisted?}, '0', '1'
  //  = pp.label :_destroy, pp.object.product.name
  //  = pp.hidden_field :product_id
  //%br

  = f.submit "Submit"
  = link_to 'Cancel', admin_promotional_codes_path

app/views/plazr_store/admin/promotional_codes/edit.html.haml
%h1 Edit Promotional Code

= render :partial => 'form'

app/views/plazr_store/admin/promotional_codes/index.html.haml
#admin
	.listing
		%h1 Lista de Códigos Promocionais
		%table.table.table-striped.table-hover.table-bordered
			%thead
				%tr
					%th Código
					%th Descrição
					%th Tipo de desconto
					%th Valor
					%th &nbsp;
					%th &nbsp;
			%tbody
				- if @promotional_codes.empty?
					%tr.info
						%td{ :colspan => 6 }
							= raw "Não existem códigos promocionais. Clique #{link_to 'aqui', new_admin_promotional_code_path} para criar um novo código."
				- else
					%tr.success
						%td{ :colspan => 6 }
							= link_to 'Adicionar código', new_admin_promotional_code_path
					- @promotional_codes.each do |promotional_code|
						%tr
							%td
								= promotional_code.code
							%td
								= promotional_code.description
							%td
								= promotional_code.value
							%td
								= promotional_code.minimum_cart
							%td
								= promotional_code.uses_allowed
							%td
								= promotional_code.times_used
							%td
								= promotional_code.starts_at
							%td
								= promotional_code.expires_at
							%td
								= promotional_code.discount_type.name
							%td
								= link_to 'Show', admin_promotional_code_path(promotional_code)
							%td
								= link_to 'Edit', edit_admin_promotional_code_path(promotional_code)
							%td
								= link_to 'Destroy', admin_promotional_code_path(promotional_code), :method => :delete, :data => { :confirm => "Está prestes eliminar o código promocional \"#{promotional_code}\". Deseja continuar?" }

app/views/plazr_store/admin/promotional_codes/new.html.haml
%h1 New Promotional Codes

= render :partial => 'form'

app/views/plazr_store/admin/promotional_codes/show.html.haml
%h1 Show Promotion
%p#notice
  = notice
%table
  %tr
    %td
      %b Name
    %td
      = @promotion.name
  %tr
    %td
      %b Description
    %td
      = @promotion.description
  %tr
    %td
      %b Value
    %td
      = @promotion.value
  %tr
    %td
      %b Minimum Filter
    %td
      = @promotion.min_filter
  %tr
    %td
      %b Start Date
    %td
      = @promotion.starts_at
  %tr
    %td
      %b End Date
    %td
      = @promotion.expires_at
  %tr
    %td
      %b Discount Type
    %td
      = @promotion.discount_type.name


= link_to 'Edit', edit_admin_promotion_path
|
= link_to 'Back', admin_promotions_path