config/routes.rb
PlazrStore::Engine.routes.draw do

  get 'index' => 'pages#index'
  # root to: 'pages#index'



  root :to => 'pages#index'

  # mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root :to => 'pages#index'
    resources :banners, :only => [:new, :create, :edit, :update]
    resources :brands
    resources :discount_types
    resources :orders, :except => [:new, :create, :edit, :update, :destroy] do
      put 'pay', :on => :member
      match 'ship/:cart_variant_id' => 'orders#ship', :as => :ship_product, :via => :put
    end
    resources :logos, :only => [:new, :create, :edit, :update]
    resources :pages
    resources :product_categories
    resources :products do
      resources :product_properties, :only => [:index, :create, :destroy]
      resources :variants
      resources :multimedia
    end
    resources :promotional_codes
    resources :promotions
    resources :properties
    resources :prototypes
    resources :shipment_conditions
    resources :template_customizations
    resources :variant_properties do
      resources :variant_property_values
    end
    resources :paypal_accounts
    match 'customization' => 'customizations#show', :as => :customization, :via => :get, :controller => 'customizations'
  end

  resources :products, :only => [:index, :show]

  #pages
  scope '/pages' do
    match 'index' => 'pages#index', :via => :get
    match '/:slug' => 'pages#show', :as => :page, :via => :get, :controller => "pages"
  end

  # search controller
  scope '/search' do
    match '/' => 'search#search', :as => :search, :via => :get, :controller => "search"
  end

  # carts controller
  scope '/cart' do
    match '/' => 'cart#show', :as => :cart, :via => :get
    match 'add/:id'    => 'cart#add',    :as => :cart_add,    :via => :post
    match 'remove/:id' => 'cart#remove', :as => :cart_remove, :via => :delete
  end

  scope '/wishlist' do
    match '/' => 'wishlist#show', :as => :wishlist, :via => :get
    match 'add/:id'    => 'wishlist#add',    :as => :wishlist_add,    :via => :post
    match 'remove/:id' => 'wishlist#remove', :as => :wishlist_remove, :via => :delete
  end

  # orders controller
  match 'checkout' => 'orders#new', :as => :checkout, :via => :get
  match 'checkout' => 'orders#create', :as => :checkout, :via => :post
  match 'express_checkout' => 'paypal_express#checkout', :as => :express_checkout
  match 'paypal_express_purchase' => 'paypal_express#purchase', :as => :paypal_express_purchase
  match "receipt" => "orders#receipt", :as => :receipt
  match 'review' => 'orders#review', :as => :review
  scope '/orders' do
    match "/" => "orders#history", :as => :orders_history
    match '/:id' => 'orders#show', :as => :order, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#new', :as => :new_feedback_product, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#create', :as => :feedback_product, :via => :post
  end


  mount PlazrAuth::Engine => '/'
end

app/models/plazr_store/product_property.rb
# encoding: utf-8
module PlazrStore
  class ProductProperty < ActiveRecord::Base
    ## Relations ##
    belongs_to :product
    belongs_to :property

    ## Attributes ##
    attr_accessible :value, :product_id, :property_id, :property, :product

    ## Validations ##
    validates :value, :presence => true

    ## Callback ##
    before_validation :unique_product_property, :on => :create

    def unique_product_property
      ProductProperty.find_by_product_id_and_property_id(self.product_id, self.property_id).nil?
    end
  end
end

app/controllers/plazr_store/admin/product_properties_controller.rb
# encoding: utf-8
module PlazrStore
  class Admin::ProductPropertiesController < Admin::ApplicationController
    before_filter :get_product

    def index
      @property = Property.new
      @property.product_properties.build
      @product_properties = @product.product_properties
    end

    def create
      @property = Property.new(params[:property])
      # updates all the product_properties already associated
      update_all_product_properties     

      # Checks if the user didn't want to enter a new ProductProperty and if it is the case
      # just get all the ProductProperties
      if (params[:property][:id_name].blank? && 
          params[:property][:product_properties_attributes]['0'][:value].blank?) 
        @product_properties = @product.product_properties
        redirect_to admin_product_product_properties_path(@product), :notice => 'Everything was updated.' 
      # checks to see if the new ProductProperty uses an existent Property and the user wants to
      # insert this value (by entering a value)
      elsif Property.exists?(:id_name => params[:property][:id_name]) && 
          !params[:property][:product_properties_attributes]['0'][:value].blank?
        # get the existent property and create the new relation
        prop = Property.find_by_id_name(params[:property][:id_name])
        ProductProperty.create(:property => prop, :product => @product,
              :value => params[:property][:product_properties_attributes]['0'][:value])  
        redirect_to admin_product_product_properties_path(@product), :notice => 'Propriedade de produto associada com sucesso. Todos os valores atualizados com sucesso.'
      # if the property fills the requirements, it is saved and then the user is redirected back to index
      elsif @property.save
        redirect_to admin_product_product_properties_path(@product), :notice => 'Propriedade de produto criada com sucesso. Todos os valores atualizados com sucesso.'
      # if everything else fails, get all the product_properties and render index
      else
        @product_properties = @product.product_properties
        render :index
      end
    end

    def destroy
      @product_property = ProductProperty.find(params[:id])
      @product_property.destroy
      redirect_to admin_product_product_properties_path(@product)
    end

    def get_location
      super
      @tab = :products
    end

    protected
      def get_product
        @product = Product.find(params[:product_id])
      end

      # iterate through each element of the hash and updates attributes of the property and
      # the product_property
      def update_all_product_properties
        params[:pps].each do |k,v|
          Property.find(v[:property_id]).update_attributes(:id_name => v[:id_name], :display_name => v[:display_name])
          ProductProperty.find(k).update_attributes(:value => v[:value])
        end if params[:pps]
      end
  end
end

app/views/plazr_store/admin/product_properties/_nav_section.html.haml
= render "plazr_store/admin/products/nav_section"

app/views/plazr_store/admin/product_properties/index.html.haml
#admin
	%h1= "Propriedades de \"#{@product.name}\""
	#properties.listing
		- if @property.errors.any?
			.alert.alert-danger
				%button.close{ :type => :button, 'data-dismiss' => :alert } &times;
				%strong= "#{pluralize(@property.errors.count, 'error')} prohibited this property from being saved:"
				%ul
					- @property.errors.full_messages.each do |msg|
						%li= msg
		%table.table.table-striped.table-hover
			%thead
				%tr
					%th.id Identificador
					%th.name Nome
					%th.value Valor
					%th.button &nbsp;
			%tbody
				= form_for([:admin, @product, @property], :url => admin_product_product_properties_path(@product), :method => :post) do |f|
					- @product_properties.each do |product_property|

						%tr
							%td.id
								= hidden_field_tag 'pps['<<product_property.id.to_s<<'][property_id]',product_property.property_id
								= text_field_tag 'pps['<<product_property.id.to_s<<'][id_name]', product_property.property.id_name
							%td.name
								= text_field_tag 'pps['<<product_property.id.to_s<<'][display_name]', product_property.property.display_name
							%td.value
								= text_field_tag 'pps['<<product_property.id.to_s<<'][value]', product_property.value
							%td.button
								= link_to 'Eliminar', admin_product_product_property_path(@product, product_property), :method => :delete, :data => { :confirm => "Está prestes a eliminar a propriedade \"#{product_property.property.id_name}\" do produto \"#{product_property.product.name}\". Deseja continuar?" }, :class => [:btn, 'btn-mini', 'btn-danger']
					%tr.new
						%td
							= f.text_field :id_name, autofocus: true, placeholder: 'Identificador'
						%td
							= f.text_field :display_name, placeholder: 'Nome'
						%td
							= f.fields_for :product_properties do |pp|
								= pp.text_field :value, placeholder: 'Valor'
								= pp.hidden_field :product_id, :value => @product.id
						%td= f.submit 'Guardar', :class => [:btn, 'btn-primary', 'btn-large']