config/routes.rb
PlazrStore::Engine.routes.draw do

  get 'index' => 'pages#index'
  # root to: 'pages#index'



  root :to => 'pages#index'

  # mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root :to => 'pages#index'
    resources :banners, :only => [:new, :create, :edit, :update]
    resources :brands
    resources :discount_types
    resources :orders, :except => [:new, :create, :edit, :update, :destroy] do
      put 'pay', :on => :member
      match 'ship/:cart_variant_id' => 'orders#ship', :as => :ship_product, :via => :put
    end
    resources :logos, :only => [:new, :create, :edit, :update]
    resources :pages
    resources :product_categories
    resources :products do
      resources :product_properties, :only => [:index, :create, :destroy]
      resources :variants
      resources :multimedia
    end
    resources :promotional_codes
    resources :promotions
    resources :properties
    resources :prototypes
    resources :shipment_conditions
    resources :template_customizations
    resources :variant_properties do
      resources :variant_property_values
    end
    resources :paypal_accounts
    match 'customization' => 'customizations#show', :as => :customization, :via => :get, :controller => 'customizations'
  end

  resources :products, :only => [:index, :show]

  #pages
  scope '/pages' do
    match 'index' => 'pages#index', :via => :get
    match '/:slug' => 'pages#show', :as => :page, :via => :get, :controller => "pages"
  end

  # search controller
  scope '/search' do
    match '/' => 'search#search', :as => :search, :via => :get, :controller => "search"
  end

  # carts controller
  scope '/cart' do
    match '/' => 'cart#show', :as => :cart, :via => :get
    match 'add/:id'    => 'cart#add',    :as => :cart_add,    :via => :post
    match 'remove/:id' => 'cart#remove', :as => :cart_remove, :via => :delete
  end

  scope '/wishlist' do
    match '/' => 'wishlist#show', :as => :wishlist, :via => :get
    match 'add/:id'    => 'wishlist#add',    :as => :wishlist_add,    :via => :post
    match 'remove/:id' => 'wishlist#remove', :as => :wishlist_remove, :via => :delete
  end

  # orders controller
  match 'checkout' => 'orders#new', :as => :checkout, :via => :get
  match 'checkout' => 'orders#create', :as => :checkout, :via => :post
  match 'express_checkout' => 'paypal_express#checkout', :as => :express_checkout
  match 'paypal_express_purchase' => 'paypal_express#purchase', :as => :paypal_express_purchase
  match "receipt" => "orders#receipt", :as => :receipt
  match 'review' => 'orders#review', :as => :review
  scope '/orders' do
    match "/" => "orders#history", :as => :orders_history
    match '/:id' => 'orders#show', :as => :order, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#new', :as => :new_feedback_product, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#create', :as => :feedback_product, :via => :post
  end


  mount PlazrAuth::Engine => '/'
end

app/models/plazr_store/variant_property_value.rb
# encoding: utf-8
module PlazrStore
  class VariantPropertyValue < ActiveRecord::Base
    # Overrides some basic methods for the current model so that calling #destroy sets a 'deleted_at' field to the current timestamp
    include PZS::ParanoiaInterface

    ## Relations ##
    belongs_to :variant_property

    has_many :variant_variant_property_values, :dependent => :destroy
    has_many :variants, :through => :variant_variant_property_values

    ## Attributes ##
    attr_accessible :name, :presentation, :variant_property_id

    ##Validations ##
    validates_presence_of :name, :variant_property
    validates :name, :uniqueness_without_deleted => true
    validates :variant_property, :presence => true

    ## Callbacks ##
    before_save :fill_fields

    def fill_fields
      self.presentation = self.name unless !self.presentation.blank?
    end
  end
end

app/controllers/plazr_store/admin/variant_property_values_controller.rb
# encoding: utf-8
module PlazrStore
  class Admin::VariantPropertyValuesController < Admin::ApplicationController
    before_filter :get_variant_property

    def show
      @variant_property_value = VariantPropertyValue.find(params[:id])
    end

    def index
      @variant_property_values = @variant_property.variant_property_values.paginate( page: params['page'], per_page: 10 )
    end

    def create
      @variant_property_value = @variant_property.variant_property_values.build params[:variant_property_value]

      if @variant_property_value.save
        redirect_to admin_variant_property_variant_property_values_path, :notice => 'Valor de propriedade de modelo criado com sucesso.'
      else
        render :new
      end
    end

    def new
      @variant_property_value = VariantPropertyValue.new
    end

    def edit
      @variant_property_value = VariantPropertyValue.find params[:id]
    end

    def update
      @variant_property_value = VariantPropertyValue.find params[:id]

      if @variant_property_value.update_attributes(params[:variant_property_value])
        redirect_to admin_variant_property_variant_property_value_path(@variant_property, @variant_property_value), :notice => 'Valor de propriedade de modelo atualizado com sucesso.'
      else
        render :edit 
      end
    end

    def destroy
      @variant_property_value = VariantPropertyValue.find(params[:id])
      @variant_property_value.destroy
      redirect_to admin_variant_property_variant_property_values_path
    end

    protected
      def get_variant_property
        @variant_property = VariantProperty.find(params[:variant_property_id])
      end

      def get_location
        super
        @tab = 'products'
      end
  end
end

app/views/plazr_store/admin/variant_property_values/_form.html.haml
= form_for [:admin, @variant_property, @variant_property_value], :html => { :class => [:form, 'form-horizontal'] } do |f|
	/ - if @variant_property_value.errors.any?
	/ 	#error_explanation
	/ 		%h2= "#{pluralize(@variant_property_value.errors.count, "error")} prohibited this variant_property_value from being saved:"
	/ 		%div{:class=>["alert","alert-error"]}
	/ 			%ul
	/ 				- @variant_property_value.errors.full_messages.each do |msg|
	/ 					%li= msg

	.control-group
		= f.label 'Nome', :class => 'control-label'
		.controls
			= f.text_field :name
	
	.control-group
		= f.label 'Apresentação', :class => 'control-label'
		.controls
			= f.text_field :presentation
	
	.control-group
		.controls
			= f.submit "Guardar", :class => [:btn, 'btn-primary']

app/views/plazr_store/admin/variant_property_values/_nav_section.html.haml
= render 'plazr_store/admin/variant_properties/nav_section'

app/views/plazr_store/admin/variant_property_values/edit.html.haml
#admin
	%h1= "Editar \"#{@variant_property_value.presentation}\""
	.btn-group
		= link_to 'Voltar', admin_variant_property_variant_property_values_path(@variant_property), :class => [:btn, 'btn-small']
	= render 'form'

app/views/plazr_store/admin/variant_property_values/index.html.haml
#admin
	%h1= "Lista de Valores para \"#{@variant_property.display_name}\""
	#variant-property-values.listing
		%table.table.table-striped.table-hover.table-bordered
			%thead
				%tr
					%th.name Nome
					%th.name Apresentação
					%th.btn-mini &nbsp;
					%th.btn-mini &nbsp;
			%tbody
				%tr.success
					%td{ :colspan => 4 }
						= link_to 'Adicionar valor', new_admin_variant_property_variant_property_value_path
				- @variant_property_values.each do |variant_property_value|
					%tr
						%td.name= variant_property_value.name
						%td.text= variant_property_value.presentation
						%td.btn-mini
							= link_to 'Editar', edit_admin_variant_property_variant_property_value_path(@variant_property, variant_property_value), :class => [:btn, 'btn-mini']
						%td.btn-mini
							= link_to 'Eliminar', admin_variant_property_variant_property_value_path(@variant_property, variant_property_value), :method => :delete, :data => { :confirm => "Está prestes a eliminar o valor \"#{variant_property_value.name}\" da propriedade de modelo \"#{@variant_property.id_name}\". Deseja continuar?" }, :class => [:btn, 'btn-mini', 'btn-danger']
		= will_paginate @variant_property_values, :renderer => BootstrapPagination::Rails

app/views/plazr_store/admin/variant_property_values/new.html.haml
#admin
	%h1= "Novo valor para \"#{@variant_property.display_name}\""
	.btn-group
		= link_to 'Voltar', admin_variant_property_variant_property_values_path(@variant_property), :class => [:btn, 'btn-small']
	= render 'form'

app/views/plazr_store/admin/variant_property_values/show.html.haml
#admin
	%h1= @variant_property_value.name
	.btn-toolbar
		.btn-group
			= link_to 'Voltar', admin_variant_property_variant_property_values_path, :class => [:btn, 'btn-small']
		.btn-group.pull-right
			= link_to 'Editar', edit_admin_variant_property_variant_property_value_path(@variant_property, @variant_property_value), :class => :btn
			= link_to 'Eliminar', admin_variant_property_variant_property_value_path(@variant_property, @variant_property_value), :method => :delete, :data => { :confirm => "Está prestes a eliminar o valor \"#{@variant_property_value.name}\" da propriedade de modelo \"#{@variant_property.id_name}\". Deseja continuar?" }, :class => [:btn, 'btn-danger']
	%h3 Apresentação
	= @variant_property_value.presentation
	%h3 Propriedade de modelo
	= link_to @variant_property_value.variant_property.display_name, admin_variant_property_path(@variant_property_value.variant_property)