config/routes.rb
PlazrStore::Engine.routes.draw do

  get 'index' => 'pages#index'
  # root to: 'pages#index'



  root :to => 'pages#index'

  # mount RedactorRails::Engine => '/redactor_rails'

  namespace :admin do
    root :to => 'pages#index'
    resources :banners, :only => [:new, :create, :edit, :update]
    resources :brands
    resources :discount_types
    resources :orders, :except => [:new, :create, :edit, :update, :destroy] do
      put 'pay', :on => :member
      match 'ship/:cart_variant_id' => 'orders#ship', :as => :ship_product, :via => :put
    end
    resources :logos, :only => [:new, :create, :edit, :update]
    resources :pages
    resources :product_categories
    resources :products do
      resources :product_properties, :only => [:index, :create, :destroy]
      resources :variants
      resources :multimedia
    end
    resources :promotional_codes
    resources :promotions
    resources :properties
    resources :prototypes
    resources :shipment_conditions
    resources :template_customizations
    resources :variant_properties do
      resources :variant_property_values
    end
    resources :paypal_accounts
    match 'customization' => 'customizations#show', :as => :customization, :via => :get, :controller => 'customizations'
  end

  resources :products, :only => [:index, :show]

  #pages
  scope '/pages' do
    match 'index' => 'pages#index', :via => :get
    match '/:slug' => 'pages#show', :as => :page, :via => :get, :controller => "pages"
  end

  # search controller
  scope '/search' do
    match '/' => 'search#search', :as => :search, :via => :get, :controller => "search"
  end

  # carts controller
  scope '/cart' do
    match '/' => 'cart#show', :as => :cart, :via => :get
    match 'add/:id'    => 'cart#add',    :as => :cart_add,    :via => :post
    match 'remove/:id' => 'cart#remove', :as => :cart_remove, :via => :delete
  end

  scope '/wishlist' do
    match '/' => 'wishlist#show', :as => :wishlist, :via => :get
    match 'add/:id'    => 'wishlist#add',    :as => :wishlist_add,    :via => :post
    match 'remove/:id' => 'wishlist#remove', :as => :wishlist_remove, :via => :delete
  end

  # orders controller
  match 'checkout' => 'orders#new', :as => :checkout, :via => :get
  match 'checkout' => 'orders#create', :as => :checkout, :via => :post
  match 'express_checkout' => 'paypal_express#checkout', :as => :express_checkout
  match 'paypal_express_purchase' => 'paypal_express#purchase', :as => :paypal_express_purchase
  match "receipt" => "orders#receipt", :as => :receipt
  match 'review' => 'orders#review', :as => :review
  scope '/orders' do
    match "/" => "orders#history", :as => :orders_history
    match '/:id' => 'orders#show', :as => :order, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#new', :as => :new_feedback_product, :via => :get
    match '/:id/feedbacks/:product_id' => 'feedback_products#create', :as => :feedback_product, :via => :post
  end


  mount PlazrAuth::Engine => '/'
end

app/models/plazr_store/product_category.rb
# encoding: utf-8
module PlazrStore
  class ProductCategory < ActiveRecord::Base
    # Overrides some basic methods for the current model so that calling #destroy sets a 'deleted_at' field to the current timestamp
    include PZS::ParanoiaInterface
    
    ## Relations ##
    # A relation to itself (categories have two levels)
    has_many :child_product_categories, class_name: "ProductCategory", foreign_key: "parent_product_category_id", :dependent => :destroy
    belongs_to :parent_product_category, class_name: "ProductCategory"

    has_many :product_product_categories, :dependent => :destroy
    has_many :products, :through => :product_product_categories
    
    ## Attributes ##
    attr_accessible :description, :name, :is_leaf, :parent_product_category_id

    ## Validations ##
    validates :name, presence: true
    validates :parent_product_category_id, presence: true, :if => :is_child?

    ## Scopes ##
    scope :parent_categories, where(:is_leaf => false)

    ## Callback ##
    before_validation :set_leaf

    
    ## Instance Methods ##
    # Gets all categories that are children of a category
    def children
      ProductCategory.where("is_leaf = ? AND parent_product_category_id = ?", true, self.id)
    end

    def is_child?
      self.is_leaf?
    end

    def set_leaf
      if self.parent_product_category_id.blank?
        self.is_leaf = false
      else
        self.is_leaf = true
      end
      true
    end
  

    ## Class Methods ##
    def self.parent_categories_without(id)
      where("is_leaf = ? AND id != ?", false, id)
    end
  end
end

app/controllers/plazr_store/admin/product_categories_controller.rb
# encoding: utf-8
module PlazrStore
  class Admin::ProductCategoriesController < Admin::ApplicationController

    def show
      @product_category = ProductCategory.find(params[:id])
    end

    def index
      @product_categories = ProductCategory.all.paginate( page: params['page'], per_page: 10 )
    end

    def new
      @product_categories = ProductCategory.parent_categories
      @product_category = ProductCategory.new
    end

    def edit
      @product_category = ProductCategory.find(params[:id])
      @product_categories = []
      if @product_category.child_product_categories.empty?
        @product_categories = ProductCategory.parent_categories_without(params[:id])
      end 
    end

    def create
      @product_category = ProductCategory.new(params[:product_category])
      if(!params[:product_category][:parent_product_category_id].empty?)
        @product_category.is_leaf = true
      end

      if @product_category.save
        redirect_to admin_product_category_path(@product_category), :notice => 'Categoria de produtos criada com sucesso.'
      else
        @product_categories = ProductCategory.where(is_leaf: false)
        render :new
      end
    end

    def update
      @product_category = ProductCategory.find(params[:id])

      if @product_category.update_attributes(params[:product_category])
        if(!params[:product_category][:parent_product_category_id].empty?)
          @product_category.is_leaf = true
        end
        redirect_to admin_product_category_path(@product_category), :notice => 'Categoria de produtos atualizada com sucesso.'
      else
        @product_categories = []
        if @product_category.child_product_categories.empty?
          @product_categories = ProductCategory.parent_categories_without(params[:id])
        end 
        render :edit
      end
    end

    def destroy
      @product_category = ProductCategory.find(params[:id])
      @product_category.destroy
      redirect_to admin_product_categories_path
    end

    def get_location
      super
      @tab = 'products'
    end
  end
end

app/views/plazr_store/admin/product_categories/_form.html.haml
= form_for [:admin, @product_category], :html => { :class => [:form, 'form-horizontal'] } do |f|
	- if @product_category.errors.any?
		#error_explanation
			%h2= "#{pluralize(@product_category.errors.count, "error")} prohibited this product_category from being saved:"
			%div{:class=>["alert","alert-error"]}
				%ul
					- @product_category.errors.full_messages.each do |msg|
						%li= msg
	.control-group
		= f.label :name, 'Nome', :class => 'control-label'
		.controls
			= f.text_field :name
	.control-group
		= f.label :description, 'Descrição', :class => 'control-label'
		.controls
			= f.text_field :description
	.control-group
		= f.label 'Categoria agregadora', :class => 'control-label'
		.controls
			= f.collection_select :parent_product_category_id, @product_categories, :id, :name, {:include_blank => true}
	.control-group
		.controls
			= f.submit 'Guardar', :class => [:btn, 'btn-primary']

app/views/plazr_store/admin/product_categories/edit.html.haml
#admin
	%h1= "Editar \"#{@product_category.name}\""
	.btn-group
		= link_to 'Voltar', admin_product_categories_path, :class => [:btn, 'btn-small']
	= render 'form'

app/views/plazr_store/admin/product_categories/index.html.haml
#admin
	%h1 Lista de Categorias
	#categories.listing
		%table.table.table-striped.table-hover.table-bordered
			%thead
				%tr
					%th.name Nome
					%th.desc Descrição
					%th.prnt Agregadora
					%th &nbsp;
					%th &nbsp;
			%tbody
				%tr.success
					%td{ :colspan => 5 }
						= link_to 'Adicionar categoria', new_admin_product_category_path
				- @product_categories.each do |pc|
					%tr
						%td.name= pc.name
						%td.desc= pc.description
						%td.prnt= pc.parent_product_category.name if pc.parent_product_category
						%td.btn-mini
							= link_to 'Editar', edit_admin_product_category_path(pc), :class => [:btn, 'btn-mini']
						%td.btn-mini= link_to 'Eliminar', admin_product_category_path(pc), :method => :delete, :data => { :confirm => "Está prestes a eliminar a categoria de produto \"#{pc.name}\". Deseja continuar?" }, :class => [:btn, 'btn-danger', 'btn-mini']
	= will_paginate @product_categories, :renderer => BootstrapPagination::Rails

app/views/plazr_store/admin/product_categories/new.html.haml
#admin
	%h1 Nova Categoria
	.btn-group
		= link_to 'Voltar', admin_product_categories_path, :class => [:btn, 'btn-small']
	= render 'form'

app/views/plazr_store/admin/product_categories/show.html.haml
#admin
	%h1= @product_category.name
	.btn-toolbar
		.btn-group
			= link_to 'Voltar', admin_product_categories_path, :class => [:btn, 'btn-small']
		.btn-group.pull-right
			= link_to 'Editar', edit_admin_product_category_path, :class => :btn
			= link_to 'Eliminar', admin_product_category_path(@product_category), :method => :delete, :data => { :confirm => "Está prestes a eliminar a categoria de produto \"#{@product_category.name}\". Deseja continuar?" }, :class => [:btn, 'btn-danger']
	%h3 Descrição
	%p= @product_category.description